@JetAir = http://localhost:5012
@token = eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6Im5XajNTSTdZMEJRYnFXd0Q3cGFrbiJ9.eyJpc3MiOiJodHRwczovL2Rldi1tMm5vdDhpbDVlcW4yMzFxLnVzLmF1dGgwLmNvbS8iLCJzdWIiOiJ6VFM4SHZpTnJ3ZHBkb09nTjl0cHBIWTRIYlpsZFV6ckBjbGllbnRzIiwiYXVkIjoiaHR0cHM6Ly9qZXQtYWlyIiwiaWF0IjoxNzQ1MDkwOTkxLCJleHAiOjE3NDUxNzczOTEsInNjb3BlIjoiZGVsZXRlOmNhdGFsb2ciLCJndHkiOiJjbGllbnQtY3JlZGVudGlhbHMiLCJhenAiOiJ6VFM4SHZpTnJ3ZHBkb09nTjl0cHBIWTRIYlpsZFV6ciJ9.qfj7fuFEEOxXqodmFIYEG6f0hkt4LDrvBB1JxVlENTGJQarKFA_V7WlXZ-HT9mPJs_FKsSpn-ala6cA9qPQxUut8Cs87k3LPjlez4iUoQ0kstrCtb92k1-KTjjvpsVkOANVOU-QppF8fsmbMgGyFK7F-mvyR9k320ZyHPThoaTUsM4uAJcLdvUqXbUurnlBS4of-DQPw1X8wAvDXmg3MVzH2VcQjUvTZKMMtjqeIOIb6vmoQVmlTmqFY7lSp2nILubMtcrsLWSkUDjDbh5H1e6r-5ajohVqBqhojwLmcabbBLneFB4rSe8FmrBq1q1MG8nTA1FJzDMgGTGVjycM6Yw

GET {{JetAir}}/weatherforecast/
Accept: application/json

###
DELETE {{JetAir}}/catalog/1
Authorization: Bearer {{token}}
Accept: application/json